### ISSUE TITLE
[FEATURE REQUEST] Support for arm64

### ISSUE THREAD

**Issue by ionutz89** [lablabs/cloudflare-exporter#11]
It will be great if you can support official multi arch image like arm64.

Use case:  Use this image in K8s on Raspberry PI 4

**Comment by martinhaus** [comment]
Hey @ionutz89 , thanks for the suggestion. 
I'll take a look at this. Feel free to make a PR if you're interested.

**Comment by ionutz89** [comment]
@martinhaus thank you for your reply. I am not sure how it works your CI/CD. 

I am using Guthub Actions as building images multi arch on other projects.

Feel free to checkout this [file](https://github.com/homeall/cloudflared/blob/main/.github/workflows/main.yml)

**Comment by FlyingHavoc** [comment]
Indeed, Support for arm64 would be greatly appreciated!
