### ISSUE TITLE
`CF_API_TOKEN` authentication no longer seems to work

### ISSUE THREAD

**Issue by jon-rei** [lablabs/cloudflare-exporter#120]
After the newest update to `v0.0.16` it seems like that the authentication with `CF_API_TOKEN` is broken.

```
level=info msg="Beginning to serve metrics on :8080/metrics"
level=fatal msg="Authentication error (10000)"
```

Unfortunately I don't see any other logs, a rollback to `v.0.0.14` is fixing it.

**Comment by arazdolski** [comment]
Cloudflare API returns `Authentication error (10000)` in case if token does not have the required scope of permissions. Try to generate a new token with `Read all resources` template

**Comment by arazdolski** [comment]
According to PR #111, starting from version 0.0.15 `Zone.Firewall Services:Read` and `Account. Account Rulesets:Read` permissions required additionally. You can just add them to your existing token. Tested myself, and it's working

https://github.com/lablabs/cloudflare-exporter/pull/111/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R30-R31

**Comment by ernestaskardzys** [comment]
I also got the same error message as @jon-rei with _0.0.16_.

Tried suggestion by @arazdolski (adding two additional permissions to my Cloudflare Token) - it did help.

**Comment by jon-rei** [comment]
Yes, I was also missing those two permissions. It was not obvious from the release notes that they were now required. Thanks for the help.
