### ISSUE TITLE
zone does not have access to the path

### ISSUE THREAD

**Issue by Hayk96** [lablabs/cloudflare-exporter#13]
Getting this error message when running the exporter
`level=error msg="graphql: zone '...' does not have access to the path"`
How can I solve this problem?

**Comment by Slapper** [comment]
Hi @Hayk96 ,

Maybe this is the case : https://github.com/lablabs/cloudflare-exporter/issues/5 (if you have a mix of free and non free cloudflare accounts )

**Comment by Hayk96** [comment]
Thank you @Slapper.  Will check it.

**Comment by Hayk96** [comment]
It's working now!
