### ISSUE TITLE
Increase $maxtime (now) 

### ISSUE THREAD

**Issue by fmalykh** [lablabs/cloudflare-exporter#18]
Hi team,
First of all thanks a lot for the amazing exporter.
There is an issue we discovered recently - we noticed that the metrics we are getting for example for `cloudflare_zone_requests_total` are almost twice lower compared to those we see in cloudflare analytics dashboard.
After some manual GraphQL querying, it turned out that cloudflare is returning partial data if you query for 3 minutes ago data.
We did a change to move the `now`value to 5 mins ago:  
`now := time.Now().Add(-300 * time.Second).UTC()`

After this the metrics from the exporter are equal to those from cloudflare dashboard.

**Comment by martinhaus** [comment]
Hey, I'll look into this. We can make this configurable. I faced the same issue when originally developing the exporter, but the 3 minutes delay was enough.

**Comment by martinhaus** [comment]
fixed in #29
