### ISSUE TITLE
healthcheck endpoint

### ISSUE THREAD

**Issue by danielmotaleite** [lablabs/cloudflare-exporter#25]
Looking to the code i do not see any healthcheck endpoint.
Should we use the /metric for it? Probably would be better to add one (or two, for both liveness and for readiness probes, if it makes any sense for this)

**Comment by martinhaus** [comment]
It would make sense to add a separate endpoint. Do you think you can make a PR with it?

**Comment by martinhaus** [comment]
solved in https://github.com/lablabs/cloudflare-exporter/pull/31
