### ISSUE TITLE
Return country code in 3 letters

### ISSUE THREAD

**Issue by ingvarch** [lablabs/cloudflare-exporter#34]
Is it possible to return country code in 3 letters (instead 2 letters) ?

I would like to use [Grafana Worldmap Panel](https://grafana.com/grafana/plugins/grafana-worldmap-panel/) but I can't because it uses geohash of 3 letters country code. 

btw, I use prometheus

Thanks

**Comment by martinhaus** [comment]
Hey, it should be possible to use 2 letter country codes according to the plugin docs.
```
The following location files are included in the plugin:

    Countries (2 letter codes)
    Countries (3 letter codes)
    US states
```

**Comment by ingvarch** [comment]
@martinhaus oh, it my bad. 

Didn't read the documentation carefully.

Thank you very much.

**Comment by ingvarch** [comment]
By the way. 
It works fine to me. 

<img width="734" alt="Screenshot 2021-08-05 at 12 21 12 PM" src="https://user-images.githubusercontent.com/1292445/128326084-d1624e54-48e5-402d-97af-c84740d65c56.png">

Thanks again.
