### ISSUE TITLE
Extend metrics with new Datasets

### ISSUE THREAD

**Issue by ldb** [lablabs/cloudflare-exporter#4]
Hello,

so far, the exporter is only using the `httpRequests1mGroups` and `httpRequests1dByColoGroups`, the latter of which is being sunset on March 1, 2021.

I'd like to suggest to extend the available metrics by also making use of the following Datasets:
- `firewallEventsAdaptiveByTimeGroups`
- `ipFlows1mAttacksGroups`
- `synAvgPps1mGroups`

I would also be happy to implement these myself and open a PR, but wanted to check interest with you first.

**Comment by martinhaus** [comment]
Hey @ldb, please feel free to implement any of the datasets you mentioned and make a PR

**Comment by martinhaus** [comment]
The `httpRequests1dByColoGroups` will be deprecated in the 0.0.4 release. 
@ldb did you have a chance to work on the other datasets?

**Comment by ldb** [comment]
Hey @martinhaus, no, not yet.

**Comment by ldb** [comment]
@martinhaus Maybe you missed it, but I opened another PR for this same issue here: https://github.com/lablabs/cloudflare-exporter/pull/8
