### ISSUE TITLE
How to add Prometheus data source in Grafana?

### ISSUE THREAD

**Issue by banchain** [lablabs/cloudflare-exporter#9]
Hi, after I execute docker run, I try to add Prometheus data source in Grafana with url: http://localhost:8080.
However, when I press "save and test", error show up "HTTP Error Not Found".

I also can't open web browser with http://localhost:8080.

Please help.

**Comment by martinhaus** [comment]
Hey @banchain, I'd suggest reading more about how Prometheus works. This is just an exporter for gathering cloudflare data, you still need a separate Prometheus instance to pull data from this exporter.

https://prometheus.io/docs/instrumenting/exporters/
