### ISSUE TITLE
Metrics are shown only for pro-domains

### ISSUE THREAD

**Issue by D13410N3** [lablabs/cloudflare-exporter#92]
Hello

I currently have 20 domains with CF pro-plan and ~80 with free.

Exporter shows statistics only for domains with pro plan and higher

The only metric I see when `FREE_TIER` is set to `TRUE` is `cloudflare_worker_cpu_time`

Is this the expected behaviour?

**Comment by Stazis555** [comment]
If you are using helm chart, then update image tag to latest or 0.0.14 (in chart it uses version 0.0.9), this will fetch metrics for free tier as well.

**Comment by tomich** [comment]
Definetly related to https://github.com/lablabs/cloudflare-exporter/issues/32

**Comment by D13410N3** [comment]
@tomich you're absolutely right, my research (free plan enabling/disabling) had confirmed it
